apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: customer-deployment
  labels:
    app: customerlabel
spec:
  replicas: 1 # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: customerlabel
  template:
    metadata:
      labels:
        app: customerlabel
    spec:
      containers:
        - name: customer-service
          image: customer-service:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1001 # The port that the container is running on in the cluster
---
apiVersion: v1
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: customer-deployment
spec:
  selector:
    app: customerlabel
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1001
      targetPort: 1001